### ISSUE TITLE
Logging can't be associated to transaction

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-downstream#19]
https://github.com/ONSdigital/sdx-downstream/blob/develop/app/helpers/ftp_helper.py#L20

Logging in this function only mentions file names which contain collection exercise and sequence numbers,  but give no context for the transaction this was associated with.

As we scale and the logs become busier, it will be important to know exactly which transactions have been processed downstream.

**Comment by necrophonic** [comment]
Has been superseded by new `sdxftp` library which logs the tx_id as required
